# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dependabot/npm_and_yarn/acorn-5.7.4

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm uninstall webpack
    rm -rf node_modules package-lock.json
    npm install --save-dev css-loader@6
    npm uninstall html-webpack-plugin
    npm install --save-dev html-webpack-plugin@5
    npm uninstall flow-bin flow-typed @babel/preset-flow eslint-plugin-flowtype
    npm run build
  displayName: 'npm install and build'
- script: |
    export NODE_OPTIONS=--openssl-legacy-provider
    npm run build
  displayName: Build with legacy OpenSSL provider
